language: dart
dart:
- dev
- stable
# Only building master means that we don't run two builds for each pull request.
dart_task:
- test: --platform vm,chrome
- dartanalyzer
- dartfmt
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
